apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reddit-ingress
  annotations:
    # Keep the rewrite target
    nginx.ingress.kubernetes.io/rewrite-target: /
    # --- ADD THESE LINES FOR CORS ---
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
spec:
  ingressClassName: nginx
  rules:
  # Rule 1: Point the root domain
  - host: thersdevelopers.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: reddit-clone-service
            port:
              number: 80
  # Rule 2: Point the 'www' subdomain
  - host: www.thersdevelopers.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: reddit-clone-service
            port:
              number: 80